// Post-build smoke test: validates the build output, then serves it through
// `vite preview` (which runs the Cloudflare workerd runtime via
// @cloudflare/vite-plugin) and checks the responses Cloudflare will serve.
import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const DIST = "dist";
const PORT = Number(process.env.SMOKE_PORT ?? 4173);
const BASE = `http://localhost:${PORT}`;
const failures = [];

function check(condition, message) {
  if (condition) {
    console.log(`  ok   ${message}`);
  } else {
    console.error(`  FAIL ${message}`);
    failures.push(message);
  }
}

// ---- 1. Static build output ----
console.log("Build output");
const indexPath = join(DIST, "index.html");
check(existsSync(indexPath), "dist/index.html exists");
const indexHtml = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : "";
check(!indexHtml.includes("/src/main.tsx"), "index.html has no dev-only /src entry");

const assetRefs = [...indexHtml.matchAll(/(?:src|href)="(\/assets\/[^"]+)"/g)].map(
  (m) => m[1]
);
check(assetRefs.length > 0, "index.html references hashed /assets bundles");
for (const ref of assetRefs) {
  check(existsSync(join(DIST, ref)), `${ref} exists on disk`);
}

const wranglerOut = join(DIST, "wrangler.json");
check(existsSync(wranglerOut), "dist/wrangler.json generated by Cloudflare plugin");
if (existsSync(wranglerOut)) {
  const cfg = JSON.parse(readFileSync(wranglerOut, "utf8"));
  check(cfg.name === "lyfie-org", `worker name is lyfie-org (got ${cfg.name})`);
  check(
    cfg.assets?.not_found_handling === "single-page-application",
    "assets.not_found_handling is single-page-application"
  );
}

// ---- 2. Served through workerd ----
console.log(`\nRuntime (vite preview on ${BASE})`);
const server = spawn(
  "pnpm",
  ["exec", "vite", "preview", "--port", String(PORT), "--strictPort"],
  {
    stdio: ["ignore", "pipe", "pipe"],
    shell: process.platform === "win32",
    // own process group on POSIX so the whole tree (pnpm -> vite -> workerd) can be killed
    detached: process.platform !== "win32"
  }
);
let serverLog = "";
server.stdout.on("data", (d) => (serverLog += d));
server.stderr.on("data", (d) => (serverLog += d));

async function waitForServer(timeoutMs = 30_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await fetch(BASE);
      return true;
    } catch {
      await new Promise((r) => setTimeout(r, 500));
    }
  }
  return false;
}

async function expect(path, { status = 200, type, contains } = {}) {
  const res = await fetch(BASE + path, { redirect: "manual" });
  const body = await res.text();
  const ct = res.headers.get("content-type") ?? "";
  check(res.status === status, `GET ${path} -> ${res.status} (want ${status})`);
  if (type) check(ct.includes(type), `GET ${path} content-type "${ct}" ~ ${type}`);
  if (contains) check(body.includes(contains), `GET ${path} body contains ${contains}`);
}

try {
  if (!(await waitForServer())) {
    check(false, "preview server started");
  } else {
    await expect("/", { type: "text/html", contains: '<div id="root">' });
    for (const ref of assetRefs) {
      await expect(ref, { type: ref.endsWith(".css") ? "text/css" : "javascript" });
    }
    await expect("/logo.png", { type: "image/png" });
    await expect("/favicon.ico");
    // SPA fallback: unknown routes must serve the app shell, not 404
    await expect("/some/deep/client-route", {
      type: "text/html",
      contains: '<div id="root">'
    });
  }
} catch (err) {
  check(false, `runtime checks threw: ${err.message}`);
} finally {
  if (process.platform === "win32") {
    spawn("taskkill", ["/pid", String(server.pid), "/T", "/F"]);
  } else {
    process.kill(-server.pid, "SIGTERM");
  }
}

if (failures.length) {
  console.error(`\n${failures.length} check(s) failed.`);
  if (serverLog) console.error("\n--- preview server output ---\n" + serverLog);
  process.exit(1);
}
console.log("\nAll smoke checks passed.");
